name: surendri
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6233754649292678
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#969594'
    - '#ffffff'
    - '#dfdfbf'
    - '#000000'
    - '#555555'
  brandStrength: 0.75
  lightness: 0.37094798404723406
  saturation: 0.4375
  rhythmicContrast: 0.8894107369706035
purpose: []
