name: surendri
favicon: null
layout_spectrum: 0.2663866225630045
typography_spectrum: 0.6233754649292678
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.865117221372202
  lightness: 0.37094798404723406
  saturation: 0.44907189067453146
  rhythmicContrast: 0.8894107369706035
purpose: []
