name: surendri
favicon: null
layout_spectrum: 1
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74406626-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#969594'
    - '#ffffff'
    - '#dfdfbf'
    - '#000000'
    - '#555555'
  brandStrength: 0.3125
  lightness: 0.6875
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
